src/Entity/Category.php
<?php

namespace App\Entity;

use App\Repository\CategoryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CategoryRepository::class)]
class Category
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $CategoryName = null;

    #[ORM\OneToMany(mappedBy: 'Category', targetEntity: Product::class)]
    private Collection $products;

    public function __construct()
    {
        $this->products = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCategoryName(): ?string
    {
        return $this->CategoryName;
    }

    public function setCategoryName(string $CategoryName): static
    {
        $this->CategoryName = $CategoryName;

        return $this;
    }

    /**
     * @return Collection<int, Product>
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Product $product): static
    {
        if (!$this->products->contains($product)) {
            $this->products->add($product);
            $product->setCategory($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): static
    {
        if ($this->products->removeElement($product)) {
            // set the owning side to null (unless already changed)
            if ($product->getCategory() === $this) {
                $product->setCategory(null);
            }
        }

        return $this;
    }
}

src/Form/CategoryType.php
<?php

namespace App\Form;

use App\Entity\Category;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CategoryType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('category_name', TextType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Category::class,
        ]);
    }
}

src/Controller/CategoryController.php
<?php

namespace App\Controller;

use App\Entity\Category;
use App\Form\CategoryType;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use function Symfony\Config\Monolog\persistent;

class CategoryController extends AbstractController
{
    #[Route('/category', name: 'app_category')]
    public function listAction(ManagerRegistry $doctrine): Response
    {
        $categories = $doctrine->getRepository( 'App\Entity\Category')->findAll();

        return $this->render('category/index.html.twig',
            ['categories' => $categories]);
    }

    #[Route('/category/create', name: 'category_create', methods: ['GET', 'POST'])]
    public function createAction(ManagerRegistry $doctrine,Request $request)
    {
        $category = new Category();
        $form = $this->createForm(CategoryType::class, $category);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $doctrine->getManager();
            $em->persist($category);
            $em->flush();

            $this->addFlash(
                'notice',
                'Category Added'
            );
            return $this->redirectToRoute('app_category');
        }
        return $this->renderForm('category/create.html.twig', ['form' => $form]);
    }
}

templates/category/create.html.twig
{% block title %}{% endblock %}

{% block stylesheets %}
    <style>
        body {
            font-family: 'Calibri', Calibri;
            font-size: 16px;
            background-color: #f5f5f5;
        }

        .container {
            padding-top: 20px;
        }

        .card {
            border: none;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        .card-body {
            padding: 20px;
        }

        .card-title {
            font-family: 'Roboto', sans-serif;
            font-size: 24px;
            font-weight: 600;
            margin-bottom: 20px;
        }

        .form-group {
            margin-bottom: 20px;
        }

        .form-control {
            border: 1px solid #dcdcdc;
            border-radius: 5px;
            box-shadow: none;
        }

        .btn-primary {
            background-color: #007bff;
            border: none;
            border-radius: 5px;
            padding: 12px 30px;
            margin-right: 10px;
        }

        .btn-primary:hover {
            background-color: #0056b3;
        }

        .btn-back {
            background-color: #33dc3f;
            border: none;
            border-radius: 5px;
            padding: 12px 30px;
        }

        .btn-back:hover {
            background-color: #c82333;
        }
    </style>
{% endblock %}

{% block body %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <h2 class="card-title text-center">Create a New Category</h2>
                        <hr>
                        {{ form_start(form) }}
                        <div class="form-group">
                            {{ form_label(form.category_name, 'Category', {'label_attr': {'class': 'control-label'}}) }}
                            {{ form_widget(form.category_name, {'attr': {'class': 'form-control'}}) }}
                        </div>
                        <div class="text-center">
                            <div class="btn-group"> <!-- Button group to place buttons in a horizontal line -->
                                <button type="submit" name="category_create" class="btn btn-primary">Create</button>
                                <a href="{{ path('app_product') }}" class="btn btn-back">Back to Product List</a>
                            </div>
                        </div>
                        {{ form_end(form) }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/category/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <a href="{{ path('category_create')}} "class='btn btn-success'>New Category</a>
    <div class="bs-example" data-example-id="striped-table">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>Category</th>

            </tr>
            </thead>
            <tbody>
            {% for category in categories %}
                <tr>
                    <th scope="row">{{ category.id }}</th>
                    <td><a href="{{path('app_category',{'id':category.id})}} ">{{ category.categoryName }}</a></td>

                    <td>
{#                        <a href="{{path('app_category',{'id':category.id})}} " class='btn btn-success'>View</a>#}
{#                        <a href="#" class='btn btn-default'>Edit</a>#}
                        {#<a href="{{ path('product_delete', {'id': category.id}) }} "class='btn btn-danger'>Delete</a>#}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}