src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $ProductName = null;

    #[ORM\Column]
    private ?int $Price = null;

    #[ORM\Column]
    private ?int $Quantity = null;

    #[ORM\Column(length: 255)]
    private ?string $Description = null;

    #[ORM\Column(length: 255)]
    private ?string $ProductImage = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $Category = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProductName(): ?string
    {
        return $this->ProductName;
    }

    public function setProductName(string $ProductName): static
    {
        $this->ProductName = $ProductName;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->Price;
    }

    public function setPrice(int $Price): static
    {
        $this->Price = $Price;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->Quantity;
    }

    public function setQuantity(int $Quantity): static
    {
        $this->Quantity = $Quantity;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): static
    {
        $this->Description = $Description;

        return $this;
    }

    public function getProductImage(): ?string
    {
        return $this->ProductImage;
    }

    public function setProductImage(string $ProductImage): static
    {
        $this->ProductImage = $ProductImage;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->Category;
    }

    public function setCategory(?Category $Category): static
    {
        $this->Category = $Category;

        return $this;
    }
}

src/Form/ProductType.php
<?php

namespace App\Form;

use App\Entity\Product;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;

class ProductType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Category',EntityType::class,array('class'=>'App\Entity\Category','choice_label'=>"CategoryName")
            )
            ->add('ProductName',TextType::class)
            //  ->remove('name')
            ->add('price',TextType::class)
            ->add('quantity',TextType::class)
            ->add('description', TextareaType::class)
            ->add('productImage', FileType::class, [
                'label' => 'Image file',
                'mapped' => false,
                'required' => false,
                'constraints' => [
                    new File([
                        'maxSize' => '1024k',
                        'mimeTypesMessage' => 'Please upload a valid image',
                    ])
                ],
            ])
        ;
    }
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Product::class,
        ]);
    }
}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Category;
use App\Entity\Product;
use App\Form\ProductType;
use Doctrine\Persistence\ManagerRegistry;
use phpDocumentor\Reflection\DocBlock\Tags\Reference\Reference;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;
use function Symfony\Config\Framework\Workflows\type;


class ProductController extends AbstractController
{
    #[Route('/', name: 'app_product')]
    public function index(ManagerRegistry $doctrine): Response
    {
        $categories = $doctrine->getRepository('App\Entity\Category')->findAll();
        $products = $doctrine->getRepository('App\Entity\Product')->findAll();
        return $this->render('product/index.html.twig', [
            'controller_name' => 'ProductController',
            'products' => $products,
            'categories' => $categories
        ]);
    }

#[Route('/category', name: 'app_category')]
    public function listAction(ManagerRegistry $doctrine): Response
    {
        $categories = $doctrine->getRepository( 'App\Entity\Category')->findAll();

        return $this->render('category/index.html.twig', ['categories' => $categories
        ]);
    }

#[route ('/product/details/{id}', name: 'product_details')]
    public function detailsAction(ManagerRegistry $doctrine, $id)
    {
        $products = $doctrine->getRepository('App\Entity\Product')->find($id);
        return $this->render('product/detail.html.twig', ['product' => $products]);
    }

#[route ('/product/delete/{id}', name: 'product_delete')]
    public function deleteAction(ManagerRegistry $doctrine, $id)
    {
        $em = $doctrine->getManager();
        $product = $em->getRepository('App\Entity\Product')->find($id);
        if (!is_null($product)) {


            $em->remove($product);
            $em->flush();

            $this->addFlash(
                'error',
                'Product deleted'
            );
        } else {
            $this->addFlash(
                'error',
                'product not existed!'
            );
        }
        return $this->redirectToRoute('app_product');
    }

    #[Route('/product/create', name:'create_product', methods:['GET', 'POST'])]
    public function createAction(ManagerRegistry $doctrine, Request $request, SluggerInterface $slugger)
    {
        $product = new Product();
        $form = $this->createForm(ProductType::class, $product);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            // uplpad file
            $productImage = $form->get('productImage')->getData();
            if ($productImage) {
                $originalFilename = pathinfo($productImage->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename . '-' . uniqid() . '.' . $productImage->guessExtension();

                // Move the file to the directory where brochures are stored
                try {
                    $productImage->move(
                        $this->getParameter('productImages_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    $this->addFlash(
                        'error',
                        'Cannot upload'
                    );// ... handle exception if something happens during file upload
                }
                $product->setProductImage($newFilename);
            } else {
                $this->addFlash(
                    'error',
                    'Cannot upload'
                );// ... handle exception if something happens during file upload
            }
            $em = $doctrine->getManager();
            $em->persist($product);
            $em->flush();

            $this->addFlash(
                'notice',
                'product Added'
            );
            return $this->redirectToroute('app_product');
        }

        return $this->renderForm('product/create.html.twig', ['form' => $form]);


    }




#[Route('/product/edit/{id}', name: 'product_edit')]
    public function editAction(ManagerRegistry $doctrine, int $id,Request $request,SluggerInterface $slugger): Response{
        $entityManager = $doctrine->getManager();
        $product = $entityManager->getRepository(Product::class)->find($id);
        $form = $this->createForm(ProductType::class, @$product);
        $form->handleRequest($request);
        $categories = $doctrine->getRepository('App\Entity\Category')->findAll();


        if ($form->isSubmitted() && $form->isValid()) {
            //upload file
            $productImage = $form->get('productImage')->getData();
            if ($productImage) {
                $originalFilename = pathinfo($productImage->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename . '-' . uniqid() . '.' . $productImage->guessExtension();
                // Move the file to the directory where brochures are stored
                try {
                    $productImage->move(
                        $this->getParameter('productImages_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    $this->addFlash(
                        'error',
                        'Cannot upload'
                    );// ... handle exception if something happens during file upload
                }
                $product->setProductImage($newFilename);
            }else{
                $this->addFlash(
                    'notice',
                    'Edit success'
                );// ... handle exception if something happens during file upload
            }

            $em = $doctrine->getManager();
            $em->persist($product);
            $em->flush();
            return $this->redirectToRoute('app_product', [
                'id' => $product->getId()
            ]);

        }
        return $this->renderForm('product/edit.html.twig', ['form' => $form]);
    }
}

templates/product/create.html.twig
{% extends '/base.html.twig' %}
{% block body %}
    <style>
        .form-group {
            margin-bottom: 20px;
        }
        label {
            display: block;
            font-weight: bold;
            margin-bottom: 5px;
        }
        input[type="text"],
        textarea {
            width: 300px;
            padding: 5px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }
        input[type="submit"] {
            padding: 10px 20px;
            background-color: #4CAF50;
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }
    </style>
    {{ form_start(form) }}
    <div class="form-group">
        <label for="category">Category</label>
        {{ form_widget(form.Category,{
            'attr':{
                'class':'form-control'
            }
        }) }}
    </div>
    <div class="form-group">
        <label for="category">Product Name:</label>
        {{ form_widget(form.ProductName,{
            'attr':{
                'class':'form-control',
                'placeholder': 'Product name'
            }
        }) }}
    </div>
    <div class="form-group">
        <label for="category">Price:</label>
        {{ form_widget(form.price,{
            'attr':{
                'class':'form-control',
                'placeholder': 'Price'
            }
        }) }}
    </div>
    <div class="form-group">
        <label for="category">Quantity:</label>
        {{ form_widget(form.quantity,{
            'attr':{
                'class':'form-control',
                'placeholder': 'Quantity'
            }
        }) }}
    </div>
    <div class="form-group">
        <label for="description">Description:</label>
        {{ form_widget(form.description,{
            'attr':{
                'class':'form-control',
                'placeholder': 'Description'
            }
        }) }}
    </div>
    <div class="form-group">
        <label for="due_date">Image</label>
        {{ form_widget(form.productImage,{

        }) }}
    </div>
    <input type="submit" name="create_product" value="Create" class="btn btn-primary"/>
    {{ form_end(form) }}
{% endblock %}

templates/product/detail.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <a href="{{ path('app_product') }}" class="btn btn-default">Back to Product List</a>
    <hr/>
    <div style="display: flex; align-items: center; justify-content: center;">
        <div>
            <h2 class="page-header">{{ product.productName }}</h2>
            <img src="{{ asset('Images/' ~ product.ProductImage) }}" alt="Product Image" style="max-width: 300px;">
            <ul class="list-group">
                <li class="list-group-item">Price: {{ product.Price }}</li>
            </ul>
            <p>{{ product.Description }}</p>
        </div>
    </div>

{% endblock %}

templates/product/edit.html.twig
{% extends '/base.html.twig' %}
{% block body %}
    <style>
        .form-group {
            margin-bottom: 20px;
        }
        label {
            display: block;
            font-weight: bold;
            margin-bottom: 5px;
        }
        input[type="text"],
        textarea {
            width: 300px;
            padding: 5px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }
        input[type="submit"] {
            padding: 10px 20px;
            background-color: #4CAF50;
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }
    </style>
    {{ form_start(form) }}
<div class="form-group">
    <label for="category">Category</label>
    {{ form_widget(form.Category,{
        'attr':{
            'class':'form-control'
        }
    }) }}
</div>
<div class="form-group">
    <label for="category">Product Name:</label>
    {{ form_widget(form.ProductName,{
        'attr':{
            'class':'form-control',
            'placeholder': 'Product name'
        }
    }) }}
</div>
<div class="form-group">
    <label for="category">Price:</label>
    {{ form_widget(form.price,{
        'attr':{
            'class':'form-control',
            'placeholder': 'Price'
        }
    }) }}
</div>
<div class="form-group">
    <label for="category">Quantity:</label>
    {{ form_widget(form.quantity,{
        'attr':{
            'class':'form-control',
            'placeholder': 'Quantity'
        }
    }) }}
</div>
<div class="form-group">
    <label for="description">Description:</label>
    {{ form_widget(form.description,{
        'attr':{
            'class':'form-control',
            'placeholder': 'Description'
        }
    }) }}
</div>
<div class="form-group">
    <label for="due_date">Image</label>
    {{ form_widget(form.productImage,{

    }) }}
</div>
    <input type="submit" name="edit_product" value="Edit" class="btn btn-primary"/>
    {{ form_end(form) }}
{% endblock %}

templates/product/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <div class="container mt-4">
        <table class="table table-striped table-bordered">
            <thead class="thead-dark">
            <tr>
                <th>#</th>
                <th>Product Name</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Description</th>
                <th>Image</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for product in products %}
                <tr>
                    <th scope="row">{{ product.id }}</th>
                    <td>{{ product.ProductName }}</td>
                    <td>{{ product.Price }}</td>
                    <td>{{ product.Quantity }}</td>
                    <td>{{ product.Description }}</td>
                    <td>
                        <a href="{{ asset('Images/' ~ product.ProductImage) }}" target="_blank">
                            <img src="{{ asset('Images/' ~ product.ProductImage) }}" alt="Product Image" class="img-thumbnail custom-thumbnail">
                        </a>
                    </td>
                    <td>
                        <a href="{{ path('product_details', {'id': product.id}) }}" class="btn btn-success">View</a>
                        <a href="{{ path('product_delete', {'id': product.id}) }}" class="btn btn-danger">Delete</a>
                        <a href="{{ path('product_edit', {'id': product.id}) }}" class="btn btn-info">Edit</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}

{% block stylesheets %}
    <style>
        .custom-thumbnail {
            max-width: 100px; /* Set the maximum width for the thumbnail */
            height: auto; /* Maintain aspect ratio */
        }
    </style>
{% endblock %}